name: Run API Tests


on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to test against'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production
      browser:
        description: 'Browser to run tests on'
        required: true
        default: 'chrome'
        type: choice
        options:
        - chrome
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pytest-cov

    - name: Run pytest with coverage
      env:
        WEKAN_URL: http://${{ secrets.HOST }}:80/users/login
        BROWSER: ${{ inputs.browser }}
      run: |
        pytest --cov=tests_r --cov-report=xml tests_r/

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: RabeeaFaraj/wekan_rabeea


